chore: refactor workflow to verify Allure report to be generated

diff --git a/.github/workflows/generate-test-report.yaml b/.github/workflows/generate-test-report.yaml
--- a/.github/workflows/generate-test-report.yaml
+++ b/.github/workflows/generate-test-report.yaml
@@ -31,7 +31,7 @@ jobs:
           wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure_2.29.0-1_all.deb
           sudo dpkg -i allure_2.29.0-1_all.deb
 
-      - name: Install Python dependencies
+      - name: Install python dependencies
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
@@ -40,20 +40,23 @@ jobs:
         run: |
           uvicorn app.main:app --host 0.0.0.0 --port 8000 &
 
+      - name: Wait for FastAPI server to be ready
+        run: |
+          while ! curl -s http://0.0.0.0:8000 > /dev/null; do
+            echo "Waiting for server..."
+            sleep 5
+          done
+
       - name: Run tests and generate Allure results
         run: |
-          pytest --alluredir=./allure-results tests/test_main.py
+          pytest --alluredir=./allure-results tests/test_main.py -v
+
+      - name: Check Allure results
+        run: ls -l ./allure-results
 
       - name: Generate Allure report
         run: |
-          allure generate ./allure-results --clean -o ./allure-report
-
-      - name: Deploy Allure report to Github Pages
-        if: success()
-        uses: peaceiris/actions-gh-pages@v4
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_dir: ./allure-report
+          allure generate ./allure-results --clean -o ./allure-report || (echo "Allure report generation failed"; exit 1)
 
       - name: Upload Allure report as artifact
         uses: actions/upload-artifact@v4
@@ -64,4 +67,4 @@ jobs:
       - name: Cleanup
         run: |
           kill $(lsof -t -i:8000)
-          rm -rf allure-results allure-report
+          rm -rf ./allure-results ./allure-report
