update: upgrade Allure commandline to version 2.34.0

diff --git a/.github/workflows/generate-test-report.yaml b/.github/workflows/generate-test-report.yaml
--- a/.github/workflows/generate-test-report.yaml
+++ b/.github/workflows/generate-test-report.yaml
@@ -28,8 +28,8 @@ jobs:
       - name: Install allure commandline
         run: |
           sudo apt-get install -y default-jre
-          wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure_2.29.0-1_all.deb
-          sudo dpkg -i allure_2.29.0-1_all.deb
+          wget https://github.com/allure-framework/allure2/releases/download/2.34.0/allure_2.34.0-1_all.deb || (echo "Failed to download Allure"; exit 1)
+          sudo dpkg -i allure_2.34.0-1_all.deb
 
       - name: Install python dependencies
         run: |
